import type { BusinessSettings, ContentMap, Product } from '../types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Toor Dal (Sample)',
    slug: 'toor-dal-sample',
    short_description: 'Premium quality toor dal — placeholder product for preview.',
    description:
      'This is placeholder product content. Replace with your actual product details through the admin panel.',
    price: 120,
    unit: 'kg',
    pack_sizes: ['500g', '1kg', '5kg'],
    features: ['Stone-free processing', 'Hygienically packed', 'Fresh stock'],
    image_url: null,
    is_available: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Moong Dal (Sample)',
    slug: 'moong-dal-sample',
    short_description: 'Split moong dal — placeholder product for preview.',
    description:
      'This is placeholder product content. Replace with your actual product details through the admin panel.',
    price: 95,
    unit: 'kg',
    pack_sizes: ['500g', '1kg'],
    features: ['Uniform size', 'Clean sorting', 'Ready to cook'],
    image_url: null,
    is_available: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Chana Dal (Sample)',
    slug: 'chana-dal-sample',
    short_description: 'Split Bengal gram — placeholder product for preview.',
    description:
      'This is placeholder product content. Replace with your actual product details through the admin panel.',
    price: 85,
    unit: 'kg',
    pack_sizes: ['1kg', '5kg', '10kg'],
    features: ['Carefully cleaned', 'Consistent quality', 'Bulk packs available'],
    image_url: null,
    is_available: false,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockContent: ContentMap = {
  hero_title: {
    id: '1',
    section_key: 'hero_title',
    title: null,
    content: 'Premium Pulses & Daal for Your Kitchen',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  hero_description: {
    id: '2',
    section_key: 'hero_description',
    title: null,
    content:
      'Placeholder — Add your business introduction here. We process and supply quality pulses with care and consistency.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  hero_cta_text: {
    id: '3',
    section_key: 'hero_cta_text',
    title: null,
    content: 'View Our Products',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  hero_supporting: {
    id: '4',
    section_key: 'hero_supporting',
    title: null,
    content: 'Trusted local pulses manufacturer — content editable from admin panel.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  home_featured_intro: {
    id: '5',
    section_key: 'home_featured_intro',
    title: 'Our Products',
    content: 'Explore our range of carefully processed pulses and daal.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  home_why_choose: {
    id: '6',
    section_key: 'home_why_choose',
    title: 'Why Choose Us',
    content:
      'Placeholder content — describe your quality standards, processing methods, and what makes your business trustworthy.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_title: {
    id: '7',
    section_key: 'about_title',
    title: 'About Us',
    content: null,
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_intro: {
    id: '8',
    section_key: 'about_intro',
    title: 'Introduction',
    content: 'Placeholder — Add your business introduction here through the admin panel.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_history: {
    id: '9',
    section_key: 'about_history',
    title: 'Our History',
    content: 'Placeholder — Share your business history when ready.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_experience: {
    id: '10',
    section_key: 'about_experience',
    title: 'Experience',
    content: 'Placeholder — Describe your years of experience in pulses manufacturing.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_mission: {
    id: '11',
    section_key: 'about_mission',
    title: 'Our Mission',
    content: 'Placeholder — Add your mission statement.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_vision: {
    id: '12',
    section_key: 'about_vision',
    title: 'Our Vision',
    content: 'Placeholder — Add your vision statement.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  about_location: {
    id: '13',
    section_key: 'about_location',
    title: 'Location',
    content: 'Placeholder — Add details about your mill location and service area.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_intro: {
    id: '14',
    section_key: 'quality_intro',
    title: 'Quality & Manufacturing',
    content: 'Placeholder — Overview of your quality and manufacturing process.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_raw_material: {
    id: '15',
    section_key: 'quality_raw_material',
    title: 'Raw Material Selection',
    content: 'Placeholder — Describe how you select raw pulses.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_cleaning: {
    id: '16',
    section_key: 'quality_cleaning',
    title: 'Cleaning',
    content: 'Placeholder — Describe your cleaning process.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_processing: {
    id: '17',
    section_key: 'quality_processing',
    title: 'Processing',
    content: 'Placeholder — Describe your processing methods.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_sorting: {
    id: '18',
    section_key: 'quality_sorting',
    title: 'Sorting',
    content: 'Placeholder — Describe your sorting standards.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_qc: {
    id: '19',
    section_key: 'quality_qc',
    title: 'Quality Control',
    content: 'Placeholder — Describe your quality checks.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_packaging: {
    id: '20',
    section_key: 'quality_packaging',
    title: 'Packaging',
    content: 'Placeholder — Describe your packaging approach.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
  quality_other: {
    id: '21',
    section_key: 'quality_other',
    title: 'Additional Information',
    content: 'Placeholder — Any other quality-related information.',
    image_url: null,
    updated_at: new Date().toISOString(),
  },
}

export const mockBusinessSettings: BusinessSettings = {
  id: '1',
  business_name: 'Your Daal Mill Name',
  phone: null,
  whatsapp: null,
  email: null,
  address: 'Placeholder address — update through admin panel',
  business_hours: 'Mon–Sat: 9:00 AM – 6:00 PM (Placeholder)',
  map_url: null,
  social_links: {},
  updated_at: new Date().toISOString(),
}
